FROM docker.io/ubuntu:22.04

ARG PYTHONBIN=python3.10
ARG USER_ID=999

ENV \
  ODOO_VERSION=18.0 \
  ODOO_BIN=odoo \
  LANG=C.UTF-8 \
  LC_ALL=C.UTF-8 \
  DEBIAN_FRONTEND=noninteractive \
  KWKHTMLTOPDF_SERVER_URL=http://kwkhtmltopdf \
  OPENERP_SERVER=/odoo/odoo.cfg \
  ODOO_RC=/odoo/odoo.cfg \
  DOCKER=false \
  ADDONS_PATH=/odoo/src/odoo/addons,/odoo/src/odoo/odoo/addons,/odoo/custom \
  PATH=/odoo/bin:$PATH \
  MODULES=base

COPY ./install /tmp/install
RUN set -x \
  && /tmp/install/pre-install.sh \
  && /tmp/install/tools.sh \
  && /tmp/install/gosu.sh \
  && /tmp/install/python3.sh \
  && /tmp/install/wkhtmltopdf.sh \
  && /tmp/install/pgdg.sh \
  && /tmp/install/dockerize.sh \
  && /tmp/install/arm64.sh \
  && /tmp/install/post-install-clean.sh \
  && rm -r /tmp/install

# Create virtualenv
RUN set -x \
  && $PYTHONBIN -m venv /odoo \
  && /odoo/bin/pip install -U click-odoo-contrib awscli

# Create odoo user
RUN adduser --home /odoo --disabled-password --shell /bin/bash -u 999 --gecos "" odoo

# Create odoo directory
RUN mkdir -p /odoo \
    && touch /odoo/odoo.cfg \
    && chown -R odoo:odoo /odoo

# Copy dockerize templates
COPY ./dockerize/${ODOO_VERSION} /templates

# Copy bin and change permissions
COPY ./bin/ /usr/local/bin/
RUN chmod +x /usr/local/bin/*

EXPOSE 8069 8072
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["odoo"]
